### PR TITLE
Added libglu

### PR DESCRIPTION
**Pull request by mashuk999**
#### Changes

- This will solve "error-while-loading-shared-libraries-libglu-so-1" message while running unity-editor.

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)

### CODE REVIEW

**Comment by webbertakken** [comment]
I'm not too sure what this is needed for. We have confirmation that people are able to run unity-editor without it.

Could you please elaborate which command you're using and what problem it solved for you exactly (except solve the error message)?

**Comment by BLaZeKiLL** [comment]
Got the same error while requesting for the manual activation file

**Comment by mashuk999** [comment]
@BLaZeKiLL `apt-get install libglu1` will solve the issue

**Comment by mashuk999** [comment]
@webbertakken I think in a plain distro the library is not present by default. libglu1 is only 500kb probably adding that will not make much difference i think

**Comment by webbertakken** [comment]
> @webbertakken I think in a plain distro the library is not present by default. libglu1 is only 500kb probably adding that will not make much difference i think

It doesn't. Except that we're republishing half a terabyte in images after this change :) Will merge it after work.

**Pull request merged**
